# Generated by Django 2.2.10 on 2020-02-23 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='グループ名')),
                ('author', models.ManyToManyField(related_name='personal_group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255, verbose_name='Todoの中身')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('importance_level', models.IntegerField(choices=[(1, 'normal'), (2, 'important'), (3, 'essential'), (4, 'crucial')])),
                ('column', models.IntegerField(choices=[(1, 'TO DO'), (2, 'IN PROGRESS'), (3, 'DONE')])),
                ('pub_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pub_in_group', to='todo.Group')),
                ('pub_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_pub_todo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
