# Generated by Django 2.2.10 on 2020-02-23 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'グループ', 'verbose_name_plural': 'グループ'},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'Todo', 'verbose_name_plural': 'Todo'},
        ),
    ]
