# Generated by Django 2.2.10 on 2020-02-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='コース')),
                ('season_name', models.CharField(help_text='何期か', max_length=10, verbose_name='時期')),
                ('department_name', models.CharField(blank=True, help_text='必要な場合のみ', max_length=40, null=True, verbose_name='部門')),
            ],
            options={
                'verbose_name': 'コース',
                'verbose_name_plural': 'コース',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='開催地')),
            ],
            options={
                'verbose_name': '開催地',
                'verbose_name_plural': '開催地',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='大学名')),
            ],
            options={
                'verbose_name': '大学',
                'verbose_name_plural': '大学',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='学部名')),
                ('university', models.ForeignKey(on_delete='CASCADE', related_name='university_faculty', to='users.University')),
            ],
            options={
                'verbose_name': '学部',
                'verbose_name_plural': '学部',
            },
        ),
    ]
