# Generated by Django 2.2.10 on 2020-02-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_course_faculty_place_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.ManyToManyField(null=True, related_name='personal_course', to='users.Course'),
        ),
        migrations.AddField(
            model_name='user',
            name='place',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='personal_place', to='users.Place'),
        ),
        migrations.AddField(
            model_name='user',
            name='university_faculty',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='personal_university_faculty', to='users.Faculty'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=40, null=True, verbose_name='コース'),
        ),
        migrations.AlterField(
            model_name='course',
            name='season_name',
            field=models.CharField(help_text='何期か', max_length=10, null=True, verbose_name='時期'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=40, null=True, verbose_name='学部名'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='university_faculty', to='users.University'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=40, null=True, verbose_name='開催地'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=40, null=True, verbose_name='大学名'),
        ),
    ]
