# Generated by Django 2.2.10 on 2020-02-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200222_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=40, verbose_name='開催地'),
        ),
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.ManyToManyField(null=True, related_name='personal_course', to='users.Course', verbose_name='コース'),
        ),
        migrations.AlterField(
            model_name='user',
            name='place',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='personal_place', to='users.Place', verbose_name='開催場所'),
        ),
        migrations.AlterField(
            model_name='user',
            name='university_faculty',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='personal_university_faculty', to='users.Faculty', verbose_name='大学・学部'),
        ),
    ]
