# Generated by Django 2.2.10 on 2020-02-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200222_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=40, verbose_name='コース'),
        ),
        migrations.AlterField(
            model_name='course',
            name='season_name',
            field=models.CharField(help_text='何期か', max_length=10, verbose_name='時期'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=40, verbose_name='学部名'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(on_delete='CASCADE', related_name='university_faculty', to='users.University'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=40, verbose_name='大学名'),
        ),
    ]
