# Generated by Django 2.2.10 on 2020-02-23 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200222_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_faculty', to='users.University'),
        ),
        migrations.AlterField(
            model_name='user',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_place', to='users.Place', verbose_name='開催場所'),
        ),
        migrations.AlterField(
            model_name='user',
            name='university_faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_university_faculty', to='users.Faculty', verbose_name='大学・学部'),
        ),
    ]
