# Generated by Django 3.0.4 on 2020-03-05 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='グループ名')),
                ('user_in_group', models.ManyToManyField(related_name='personal_group', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'グループ',
                'verbose_name_plural': 'グループ',
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255, verbose_name='Todoの中身')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('importance_level', models.IntegerField(choices=[(1, 'normal'), (2, 'important'), (3, 'essential'), (4, 'crucial')])),
                ('row', models.IntegerField(blank=True, null=True)),
                ('deadline', models.DateTimeField()),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_in_column', to='todo.Column')),
                ('pub_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pub_in_group', to='todo.Group')),
                ('pub_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_pub_todo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todo',
            },
        ),
    ]
