# Generated by Django 3.0.4 on 2020-03-05 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'verbose_name': 'カラム', 'verbose_name_plural': 'カラム'},
        ),
    ]
