# Generated by Django 3.0.4 on 2020-03-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200305_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='column',
            field=models.ManyToManyField(related_name='column_in_group', to='todo.Column'),
        ),
    ]
