# Generated by Django 3.0.4 on 2020-03-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_group_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='column',
            field=models.ManyToManyField(null=True, related_name='column_in_group', to='todo.Column'),
        ),
    ]
