# Generated by Django 3.0.4 on 2020-03-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20200306_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='column',
            field=models.ManyToManyField(blank=True, null=True, related_name='column_in_group', to='todo.Column'),
        ),
    ]
