# Generated by Django 3.0.4 on 2020-03-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20200306_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='column',
            field=models.ManyToManyField(related_name='column_in_group', to='todo.Column'),
        ),
    ]
