# Generated by Django 3.0.4 on 2020-03-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True, verbose_name='誕生日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.ManyToManyField(null=True, related_name='personal_course', to='users.Course', verbose_name='コース'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(1, '男性'), (2, '女性')], null=True, verbose_name='性別'),
        ),
    ]
