# Generated by Django 3.0.4 on 2020-03-05 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200305_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='place',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_place', to='users.Place', verbose_name='開催場所'),
        ),
    ]
